#!/bin/sh

COMMIT=HEAD
DATE=$(date +"%04Y%02m%02d")
GITVER=$(git rev-list --no-walk --abbrev-commit $COMMIT)

print()
{
cat << EOF
%global commit ${GITVER}
%global date ${DATE}
EOF
}

update()
{
sed -e "s/^%global commit [[:xdigit:]]\+/%global commit ${GITVER}/" \
	-e "s/^%global date [[:digit:]]\+/%global date ${DATE}/" -i *.spec
}

print

[ "$1" = '-u' ] && update
