.\" (C) Copyright 2014 Dariusz Dwornikowski <dariusz.dwornikowski@cs.put.poznan.pl>,
.TH RACEINTOSPACE 1 "May 15, 2014"
.SH NAME
raceintospace \- a software version of LiftOff 
.SH SYNOPSIS
.B raceintospace 
.RI [ options ]
.br
.SH DESCRIPTION
Race into Space is the free software version of Interplay's Buzz Aldrin's Race into Space. This is
the reworked version following the source release for the computer version of the Liftoff! board
game by Fritz Bronner. This was developed by Strategic Visions and published by Interplay as a
disk-based game in 1992 and a CD-ROM in 1994.
.B raceintospace
and
.B bar
commands.
.PP
.SH OPTIONS
.TP
.B \-h
Show available options. 
.TP
.B \-v
Be verbose
.TP
.B \-i
Start game in menu screen
.TP
.B \-f
Start fullscreen mode.
.SH SEE ALSO
Website: http://www.raceintospace.org/

